# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ECF Build for DarkLight

on:
  push:
    branches: [ darklight ]
  pull_request:
    branches: [ darklight ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: GitHub Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: champtc # env variable for username in deploy
        server-password: ${{ secrets.GITHUB_TOKEN }} # env variable for token in deploy

    - name: Build with Maven
      run: mvn clean deploy -f ./pom.xml -Dtycho.localArtifacts=ignore -Dmaven.test.skip=true -Dtarget-platform=2022-03
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}